### ISSUE TITLE
Refactor (Person), from length 3 array -> to { literal object }

### ISSUE THREAD

**Issue by theRemix** [owen28299/meanRevertingBeuller#1]
currently, a "Person" (in the peopleInstances array) are instantiated as a series of 3 values in an array `[0,0,0]` on line: 13

those values do not _really_ have much in common.

It would be better to give these values meaning, and by identifying meaning, you should also see that one of those values do not need to be stored in the object.

I propose to instantiate the "Person" as an object such as

```
peopleInstances[people[i]] = {
  currentScore : 0,
  randomScore : 0
};
// or name them whatever you want, that makes sense to you
```

notice though that you do not really need to store the intermediary second value `(mean - currentScore)`, as it immediately gets used to derive the third value `randomScore`, and is never accessed again.

this optional refactoring should result in more readable, understandable, maintainable, and extensible code.

difficulty: :star: :star:

**Comment by owen28299** [comment]
Done - turned into an object instead of an array of 3.
