### ISSUE TITLE
Create a form to change the student roster

### ISSUE THREAD

**Issue by theRemix** [owen28299/meanRevertingBeuller#2]
the defaults `var students` is fine, since that is the default use case.

what if a student is absent for today?

I propose adding a mechanism for the user to update the student array (which should also update the `peopleInstances`)

this optional update should be a good exercise for using the dom to manipulate data in memory (your data store).

very optional: maybe a form to add student names?

difficulty: :star: :star: :star:

**Comment by owen28299** [comment]
Students are now added dynamically to the app via the form at the top
